# Site settings
title: Jonlitwack
email: jon@jonlitwack.com
author: Jon Litwack
description: "Thoughts direct from my brain to your eyeballs."
baseurl: ""
url: "https://jonlitwack.com"
date_format: "%b %-d, %Y"
header_pages: []

# Google services
google_verification: null
google_analytics: null
google_tag_manager: null
bing_verification: null

# Optional features
animated: false
show_related_posts: false
show_post_footers: false
show_social_icons: false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
post_preview_image: false

# Facebook Page integration
fb_page: false
fb_page_id: null

# Disqus post comments
disqus_shortname: null

# Facebook Comments plugin
facebook_comments: null
facebook_appid: null
facebook_comments_number: 10

# Social icons
github_username: null
reddit_username: null
bitbucket_username: null
stackoverflow_id: null
twitter_username: null
skype_username: null
steam_nickname: null
google_plus_id: null
linkedin_username: null
angellist_username: null
medium_id: null
bitcoin_url: null
paypal_url: null
flattr_button: null
telegram_username: null
vk_id: null

# Post sharing icons
show_sharing_icons: false
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text: 'Share this post!'
    facebook: 'Share on Facebook'
    twitter: 'Share on Twitter'
    googleplus: 'Share on Google+'
    linkedin: 'Share on LinkedIn'
    digg: 'Share on Digg'
    tumblr: 'Share on Tumblr'
    reddit: 'Share on Reddit'
    stumbleupon: 'Share on StumbleUpon'
    hackernews: 'Share on Hacker News'
  post:
    updated: 'Updated'
    minute_read: 'minute read'
    related_posts: 'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email: 'Email Address'
    content: 'What would you like to say?'
    subject: 'New submission!'
    submit: 'Say Hello'
    ajax:
      sending: 'sending..'
      sent: 'Message sent!'
      error: 'Error!'
  thanks: 'Thanks for contacting me. I will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty
paginate: 4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
