# Site settings
title: Jon Litwack
email: jon@jonlitwack.com
author: Jon Litwack
description: "Global experience design leader with expertise in data strategy and AI-powered development. Transforming organizations through data-informed experience design and AI-powered development."
baseurl: ""
url: "https://jonlitwack.com"
date_format: "%b %-d, %Y"
lang: en

# Author information
author:
  name: Jon Litwack
  bio: >-
    Global experience design leader with dual expertise in 
    data strategy and AI-powered development.

# Social media
# twitter_username: null
linkedin_username: null
github_username: null
# Other social accounts from old config
reddit_username: null
bitbucket_username: null
stackoverflow_id: null
skype_username: null
steam_nickname: null
google_plus_id: null
angellist_username: null
medium_id: null
bitcoin_url: null
paypal_url: null
flattr_button: null
telegram_username: null
vk_id: null

# Google services
google_verification: null
google_analytics: null
google_tag_manager: null
bing_verification: null

# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults (front matter defaults)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

# Dark mode default (true = dark, false = light)
dark_mode_default: false

# Pagination settings
paginate: 4
paginate_path: "/insights/page:num/"

# Optional features
animated: false
show_related_posts: true
show_post_footers: false
show_social_icons: true
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
post_preview_image: false

# Post sharing icons
show_sharing_icons: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
  - new_theme
  - .sass-cache
  - .jekyll-cache
  - _projects
